language: ruby
sudo: false
dist: trusty
cache: bundler
addons:
  postgresql: 9.5
services:
  - postgresql
before_script:
- psql -c 'create database correspondence_platform_test;' -U postgres
script:
- bundle exec rubocop
- bundle exec rails db:create db:structure:load
- bundle exec rails spec
