language: ruby
sudo: false
cache: bundler
addons:
  postgresql: 9.4
services:
  - postgresql
before_script:
- psql -c 'create database correspondence_platform_test;' -U postgres
script:
- bundle exec rake rubocop
- bundle exec rake db:create db:schema:load
