version: '2'
services:
  db:
    image: postgres:9.5-alpine
  redis:
    image: redis:alpine
  web:
    build:
      args:
        development_mode: "true"
      context: .
    container_name: cts_web
    environment:
      DATABASE_URL: postgres://postgres@db/correspondence_platform_development
      DOCKER_STATE: development-setup
      RAILS_ENV: development
      REDIS_URL: redis://redis/
      SHOW_BETTER_ERRORS_TO: 172.18.0.0/16
    volumes:
      - .:/usr/src/app
      - ~/.aws:/root/.aws
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  mailer:
    build:
      args:
        development_mode: "true"
        PUMA_PORT: ""
      context: .
    command: ./run-mailer.sh
    container_name: cts_mailer
    environment:
      DATABASE_URL: postgres://postgres@db/correspondence_platform_development
      RAILS_ENV: development
      REDIS_URL: redis://redis/
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - redis
  uploads:
    build:
      args:
        additional_packages: clamav clamav-daemon clamav-freshclam libreoffice
        development_mode: "true"
      context: .
    command: ./run-uploads.sh
    container_name: cts_uploads
    environment:
      DATABASE_URL: postgres://postgres@db/correspondence_platform_development
      RAILS_ENV: development
      REDIS_URL: redis://redis/
    volumes:
      - .:/usr/src/app
      - ~/.aws:/root/.aws
    depends_on:
      - db
      - redis
  reports:
    build:
      args:
        development_mode: "true"
        PUMA_PORT: ""
      context: .
    command: ./run-reports.sh
    container_name: cts_reports
    environment:
      DATABASE_URL: postgres://postgres@db/correspondence_platform_development
      RAILS_ENV: development
      REDIS_URL: redis://redis/
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - redis

