version: '2'
services:
  db:
    image: postgres:9.5-alpine
  redis:
    image: redis:alpine
  web:
    build:
      context: .
      dockerfile: Dockerfile.development
    environment:
      DATABASE_URL: postgres://postgres@db/correspondence_platform_development
      RAILS_ENV: development
      REDIS_URL: redis://redis/
      SHOW_BETTER_ERRORS_TO: 172.18.0.0/16
    volumes:
      - .:/usr/src/app
      - ~/.aws:/root/.aws
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  mailer:
    build:
      context: .
      dockerfile: Dockerfile.mailer
    environment:
      DATABASE_URL: postgres://postgres@db/correspondence_platform_development
      RAILS_ENV: development
      REDIS_URL: redis://redis/
    command: run-mailer.sh
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - redis
  uploads:
    build:
      context: .
      dockerfile: Dockerfile.uploads
    environment:
      DATABASE_URL: postgres://postgres@db/correspondence_platform_development
      RAILS_ENV: development
      REDIS_URL: redis://redis/
    volumes:
      - .:/usr/src/app
      - ~/.aws:/root/.aws
    depends_on:
      - db
      - redis
  reports:
    build:
      context: .
      dockerfile: Dockerfile.reports
    environment:
      DATABASE_URL: postgres://postgres@db/correspondence_platform_development
      RAILS_ENV: development
      REDIS_URL: redis://redis/
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - redis

