case_uploads_s3_bucket: "correspondence-staff-case-uploads-testing"
case_uploads_accepted_types:
- application/pdf
- application/msword
- application/vnd.openxmlformats-officedocument.wordprocessingml.document
- application/vnd.ms-excel
- application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
- application/vnd.oasis.opendocument.text
- text/rtf
- application/rtf
- image/jpeg
- image/png
- image/tiff
- image/bmp
- image/gif
- image/x-bitmap
attachments_presigned_url_expiry: 900

# These are set in run.sh
git_source:  Git Source Not Available
build_date:  Build Date Not Available
git_commit:  Git Commit Not Available

cts_email_url: http://localhost
cts_email_port: 3000

s3_upload_max_tries: 5

govuk_notify_api_key: 'never-put-real-api-key-here-use-env-vars'
new_assignment_notify_template: '6f4d8e34-96cb-482c-9428-a5c1d5efa519'
reset_password_instructions_notify_template: '705029c9-d7e4-47a6-a963-944cb6d6b09c'

foi_cases:
  default_managing_team: Disclosure BMT
  default_clearance_team: Disclosure

default_date_format: '%-d %b %Y'
default_time_format: '%d %b %Y %H:%M'

press_office_team_name: Press Office
private_office_team_name: Private Office
press_office_default_user: Preston Offman
private_office_default_user: Primrose Offord

global_navigation:
  default_urls:
    approver: /cases/open?timeliness=in_time
    manager: /cases/open?timeliness=in_time
    responder: /cases/open?timeliness=in_time
  pages:
    closed_cases:
      path: /cases/closed
    incoming_cases_dacu_disclosure:
      path: /cases/incoming
    incoming_cases_press_office:
      path: /cases/incoming
    incoming_cases_private_office:
      path: /cases/incoming
    my_open_cases:
      path: /cases/my_open
    open_cases:
      path: /cases/open
    stats:
      path: /stats
    settings:
      path: /teams

  tabs:
    in_time:
      params:
        timeliness: in_time
    late:
      params:
        timeliness: late

  structure:
    'Disclosure':
      incoming_cases_dacu_disclosure: default
      open_cases:
        in_time:
        late:
      my_open_cases:
      closed_cases:

    'Press Office':
      incoming_cases_press_office: default
        # expires_today:
        # expires_tomorrow:
        # expires_in_two_days:
      open_cases:
        in_time:
        late:
      my_open_cases:
      closed_cases:

    'Private Office':
      incoming_cases_private_office: default
        # expires_today:
        # expires_tomorrow:
        # expires_in_two_days:
      open_cases:
        in_time:
        late:
      my_open_cases:
      closed_cases:

    'manager':
      open_cases:
        in_time: default
        late:
      my_open_cases:
      closed_cases:
      settings:
      stats:

    '*':
      open_cases:
        in_time: default
        late:
      my_open_cases:
      closed_cases:

