case_uploads_s3_bucket: "correspondence-staff-case-uploads-testing"
case_uploads_accepted_types:
- application/pdf
- application/msword
- application/vnd.openxmlformats-officedocument.wordprocessingml.document
- application/vnd.ms-excel
- application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
- application/vnd.oasis.opendocument.text
- text/rtf
- application/rtf
- image/jpeg
- image/png
- image/tiff
- image/bmp
- image/x-bitmap
attachments_presigned_url_expiry: 900

# These are set in run.sh
git_source:  Git Source Not Available
build_date:  Build Date Not Available
git_commit:  Git Commit Not Available

cts_email_url: http://localhost
cts_email_port: 3000

s3_upload_max_tries: 5
s3_upload_retry_delay_minutes: 5

govuk_notify_api_key: never-put-real-api-key-here-use-env-vars
new_assignment_notify_template: '6f4d8e34-96cb-482c-9428-a5c1d5efa519'
